# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LoadLocalHtml' do
 pod 'Cordova'

 # Cordova Core Plugin Dependency Pod References

 pod 'CordovaPlugin-console'
 pod 'cordova-plugin-camera'
 pod 'cordova-plugin-contacts'
 pod 'cordova-plugin-device'
 pod 'cordova-plugin-device-orientation'
 pod 'cordova-plugin-device-motion'
 pod 'cordova-plugin-globalization'
 pod 'cordova-plugin-geolocation'
 pod 'cordova-plugin-file'
 pod 'cordova-plugin-media-capture'
 pod 'cordova-plugin-network-information'
 pod 'cordova-plugin-splashscreen'
 pod 'cordova-plugin-inappbrowser'
 pod 'cordova-plugin-file-transfer'
 pod 'cordova-plugin-statusbar'
 pod 'cordova-plugin-vibration'

 # The following includes the PhoneGap iOS Platform Project Template for a quick start
 pod 'phonegap-ios-template'

  # Pods for LoadLocalHtml

end
